import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Header from '../components/Header'
import Footer from '../components/Footer'
import WorkoutProvider from "../context/WorkoutContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <WorkoutProvider>
          <Header />
          {children}
          <Footer />
        </WorkoutProvider>
      </body>
    </html>
  );
}
